### ISSUE TITLE
how to training?

### ISSUE THREAD

**Issue by phanxuanphucnd** [mmahbub/BioADAPT-MRC#2]
Hi @mmahbub ,

i want train model in the your paper. Do you guide `how to training the model`? 

Thanks you

**Comment by mmahbub** [comment]
Hi @phanxuanphucnd, 

Thank you for your interest in the project. The model was trained using the standard MRC-training pipeline (largely inspired from huggingface). I will include the pipeline shortly in a `dev` branch.

Thanks!
